
version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
  webhook:
    image: python:3.11-slim
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install flask requests && flask --app payment run --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
